name: Build Kivy Android APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull Buildozer Docker image
        run: docker pull kivy/buildozer:latest

      - name: Build APK
        run: |
          docker run --rm \
            --user root \
            -v ${{ github.workspace }}:/home/user/app \
            -w /home/user/app \
            kivy/buildozer:latest \
            android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
