name: Build Kivy Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker pull ghcr.io/kivy/buildozer

      - name: Build APK
  run: |
    docker run --rm \
      --entrypoint /bin/bash \
      -v ${{ github.workspace }}:/home/user/hostcwd \
      ghcr.io/kivy/buildozer \
      -c "cd /home/user/hostcwd && buildozer android debug"



      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
